# Generated by Django 5.0.6 on 2024-07-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaupload',
            name='details',
            field=models.TextField(default='No details provided'),
        ),
        migrations.AlterField(
            model_name='mediaupload',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
        migrations.AlterField(
            model_name='mediaupload',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
    ]
